# Generated by Django 2.1 on 2018-10-31 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monstruo', '0002_auto_20181030_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.IntegerField()),
                ('niveldesbloqueado', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('reciclador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monstruo.Reciclador')),
            ],
        ),
    ]
