# Generated by Django 2.1 on 2018-11-10 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monstruo', '0003_partida'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=500)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='img/fotosapp/')),
                ('caneca1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caneca1', to='monstruo.Caneca')),
                ('caneca2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caneca2', to='monstruo.Caneca')),
                ('caneca3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caneca3', to='monstruo.Caneca')),
            ],
        ),
    ]
