# Generated by Django 2.1 on 2018-11-16 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monstruo', '0004_nivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciclador',
            name='tipoReciclador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monstruo.TipoReciclador'),
        ),
    ]
