# Generated by Django 2.1 on 2018-11-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monstruo', '0006_auto_20181115_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residuo',
            name='caneca',
        ),
        migrations.AddField(
            model_name='residuo',
            name='caneca',
            field=models.ManyToManyField(to='monstruo.Caneca'),
        ),
    ]
